option(SIMNET_WARNINGS_AS_ERRORS "Treat compiler warnings as errors" ON)
option(SIMNET_ENABLE_TRACY "Enable Tracy profiling integration" ON)
option(SIMNET_ENABLE_RENDER "Build render support" ON)
option(SIMNET_ENABLE_SYNTHETIC "Build synthetic research workload support" OFF)
option(SIMNET_ENABLE_ASAN "Enable AddressSanitizer" OFF)
option(SIMNET_ENABLE_UBSAN "Enable UndefinedBehaviorSanitizer" OFF)
option(SIMNET_ENABLE_STRICT_WARNINGS "Enable advisory extended compiler warnings" OFF)
option(SIMNET_ENABLE_ANALYSIS_TARGETS "Add repository tooling targets" OFF)
