option(SIMNET_WARNINGS_AS_ERRORS "Treat compiler warnings as errors" OFF)
option(SIMNET_ENABLE_TRACY "Enable Tracy profiling integration" ON)
option(SIMNET_ENABLE_RENDER "Build render support" ON)
option(SIMNET_ENABLE_BENCHMARKING "Build benchmarking support" ON)
option(SIMNET_ENABLE_ENET "Build ENet transport support" ON)
option(SIMNET_ENABLE_LOCAL_IPC "Build local IPC transport support" OFF)
